const products=[{"name": "Aero Pro X", "cat": "Audio", "price": 179, "desc": "Wireless ANC headphones", "icon": "🎧"}, {"name": "Orbit Watch S", "cat": "Wearables", "price": 249, "desc": "AMOLED smart watch", "icon": "⌚"}, {"name": "Nova Keys 75", "cat": "Setup", "price": 129, "desc": "Mechanical keyboard", "icon": "⌨️"}, {"name": "Pulse Mini", "cat": "Audio", "price": 89, "desc": "Portable speaker", "icon": "🔊"}, {"name": "Arc Mouse Pro", "cat": "Setup", "price": 79, "desc": "Precision wireless mouse", "icon": "🖱️"}, {"name": "Halo Light Bar", "cat": "Home", "price": 69, "desc": "Smart ambient lighting", "icon": "💡"}, {"name": "Flux Charger 3", "cat": "Mobile", "price": 59, "desc": "3-in-1 charging station", "icon": "⚡"}, {"name": "Frame One", "cat": "Home", "price": 199, "desc": "Smart digital frame", "icon": "▣"}];
let cart=JSON.parse(localStorage.getItem('nova-cart')||'[]'), wishes=new Set(JSON.parse(localStorage.getItem('nova-wish')||'[]'));
const grid=document.querySelector('#grid');
function render(cat='Alle'){grid.innerHTML=products.filter(p=>cat==='Alle'||p.cat===cat).map(p=>`<article class="card"><button class="heart" data-wish="${p.name}">${wishes.has(p.name)?'♥':'♡'}</button><div class="visual quick" data-name="${p.name}">${p.icon}</div><div class="info"><small>${p.cat}</small><h3>${p.name}</h3><div class="priceRow"><strong>${p.price} €</strong><button class="add" data-add="${p.name}">+</button></div></div></article>`).join('');bind()}
function bind(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>wish(b.dataset.wish));document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>showProduct(b.dataset.name))}
function add(name){cart.push(name);save();openCart()};function wish(name){wishes.has(name)?wishes.delete(name):wishes.add(name);localStorage.setItem('nova-wish',JSON.stringify([...wishes]));document.querySelector('#wishCount').textContent=wishes.size;render(document.querySelector('.chips .active')?.dataset.cat||'Alle')}
function save(){localStorage.setItem('nova-cart',JSON.stringify(cart));document.querySelector('#cartCount').textContent=cart.length;renderCart()}
function renderCart(){let total=0;document.querySelector('#cartItems').innerHTML=cart.length?cart.map((n,i)=>{let p=products.find(x=>x.name===n);total+=p.price;return `<div class="cartItem"><div class="cartIcon">${p.icon}</div><div><b>${p.name}</b><small>${p.cat} · ${p.price} €</small></div><button data-remove="${i}">×</button></div>`}).join(''):'<p style="color:#777">Dein Warenkorb ist noch leer.</p>';document.querySelector('#total').textContent=total+' €';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);save()})}
const overlay=document.querySelector('#overlay'),drawer=document.querySelector('#cart'),modal=document.querySelector('#modal');function openCart(){drawer.classList.add('open');overlay.classList.remove('hidden')}function closeAll(){drawer.classList.remove('open');overlay.classList.add('hidden');modal.classList.add('hidden')};document.querySelector('#cartBtn').onclick=openCart;document.querySelector('.close').onclick=closeAll;overlay.onclick=closeAll;document.querySelector('.modalClose').onclick=closeAll;
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.cat)});
function showProduct(name){let p=products.find(x=>x.name===name);document.querySelector('#modalBody').innerHTML=`<div class="modalProduct"><div class="emoji">${p.icon}</div><small>${p.cat}</small><h2>${p.name}</h2><p>${p.desc}. Premium verarbeitet, schnell geliefert und mit 2 Jahren Garantie.</p><h3>${p.price} €</h3><button class="primary" id="modalAdd">In den Warenkorb →</button></div>`;modal.classList.remove('hidden');overlay.classList.remove('hidden');document.querySelector('#modalAdd').onclick=()=>{add(name);modal.classList.add('hidden')}}
document.querySelector('#searchBtn').onclick=()=>{document.querySelector('#modalBody').innerHTML=`<h2>Produkte suchen</h2><input id="searchInput" class="searchInput" autofocus placeholder="z.B. Audio, Watch, Charger..."><div id="results"></div>`;modal.classList.remove('hidden');overlay.classList.remove('hidden');let inp=document.querySelector('#searchInput');inp.oninput=()=>{let q=inp.value.toLowerCase();document.querySelector('#results').innerHTML=products.filter(p=>(p.name+p.cat).toLowerCase().includes(q)).map(p=>`<p><b>${p.icon} ${p.name}</b> — ${p.price} €</p>`).join('')}};
document.querySelector('#filterBtn').onclick=()=>{document.querySelector('#modalBody').innerHTML='<h2>Filter & Sortieren</h2><p>Demo-Funktion: Kategorie-Filter stehen direkt über den Produkten bereit.</p><button class="primary modalDone">Verstanden</button>';modal.classList.remove('hidden');overlay.classList.remove('hidden');document.querySelector('.modalDone').onclick=closeAll};
document.querySelector('#checkout').onclick=()=>{if(!cart.length)return;drawer.classList.remove('open');document.querySelector('#modalBody').innerHTML=`<h2>Checkout</h2><p>Sichere Demo-Bestellung</p><div class="checkoutSteps"><input placeholder="Vor- und Nachname"><input placeholder="E-Mail"><input placeholder="Straße & Hausnummer"><input placeholder="PLZ / Ort"><input placeholder="Kartennummer (Demo)"><button class="primary" id="pay">${document.querySelector('#total').textContent} sicher bezahlen →</button></div>`;modal.classList.remove('hidden');document.querySelector('#pay').onclick=()=>{cart=[];save();document.querySelector('#modalBody').innerHTML='<div class="success"><b>✓</b><h2>Bestellung bestätigt</h2><p>Demo-Bestellung #NV-2026-1048 wurde erfolgreich erstellt.</p></div>'}};
document.querySelector('#news').onsubmit=e=>{e.preventDefault();e.target.innerHTML='<strong>✓ Willkommen bei NOVA — dein 10%-Code: NOVA10</strong>'};document.querySelector('#wishCount').textContent=wishes.size;save();render();